version: '3'
services:
  backend:
    build:
      context: ./VISION-Management
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
  frontend:
     build:
      context: ./VISION-Management/frontend
      dockerfile: Dockerfile
     ports:
      - '3000:3000'
